[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

[[main]]
  name = "Categories"
  url = "/categories/"
  weight = 4

[[main]]
  name = "About"
  url = "/about/"
  weight = 5