baseURL = 'https://stephenx0r.github.io/'
languageCode = 'en-us'
title = 'Stephenx0r - CTF Writeups'
theme = 'paper'

[params]
  # Site description
  description = "Cybersecurity blog featuring detailed CTF writeups and security research"
  
  # Author information
  author = "Stephen Waweru"
  authorLink = "https://github.com/Stephenx0r"
  
  # Social links
  github = "Stephenx0r"
  linkedin = "stephengathumbi"
  
  # Site features
  showReadingTime = true
  showWordCount = true
  showPostNav = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  
  # Appearance
  fontSize = "16px"
  fontFamily = "ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif"
  
  # Code highlighting
  codeFences = true
  highlight = true
  
  # Menu
  [[params.menu]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[params.menu]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  
  [[params.menu]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  
  [[params.menu]]
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true
    tabWidth = 2
